/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { BlockKind } from "@/shared/catalog/seatmap-document";
import { BLOCK_DRAG_TYPE, type BlockGeometry, type BlockTarget, formatBlockDrag } from "./documentOps";

/**
 * What the organizer can add to a chart.
 *
 * One list rather than the three palettes it replaces (`ElementPalette`, `TablePalette` and the
 * drawing-tool rail): a stage, a block of seats and a GA zone are all just blocks, and splitting them
 * across panels meant the organizer had to know which kind of thing they wanted before they could find
 * where to add it.
 *
 * Shapes and colour live here for the same reason. A shape is a block that happens to be drawn from an
 * outline — it has nothing to do with seats and does not need any to exist — so making one belongs where
 * every other block is made, not on the app's toolbar beside Save and Publish. Colour follows it: it is
 * a property of the block, so it is offered next to the blocks it applies to.
 *
 * Tables are absent on purpose. Their seats are generated by the server so they sit outside the table's
 * edge, so they keep their own endpoint and their own palette; putting them here would imply they work
 * like the rest, and then a re-count would behave differently from every other block.
 */

const GROUPS: { title: string; items: { kind: BlockKind; glyph: string; label: string; hint: string }[] }[] = [
  {
    title: "Ghế",
    items: [
      { kind: "seating-block", glyph: "▦", label: "Khối ghế", hint: "Nhiều hàng × nhiều ghế, sửa lại được sau" },
      { kind: "single-row", glyph: "▭", label: "Một hàng", hint: "Một hàng ghế thẳng" },
      { kind: "curved-row", glyph: "◠", label: "Hàng cong", hint: "Các hàng uốn theo bán kính và góc cung" },
      { kind: "individual-seat", glyph: "•", label: "Ghế lẻ", hint: "Một ghế đơn, đặt ở đâu cũng được" },
    ],
  },
  {
    title: "Khu đứng",
    items: [{ kind: "ga-zone", glyph: "▩", label: "Khu đứng", hint: "Bán theo sức chứa, không theo từng ghế" }],
  },
  {
    title: "Trang trí",
    items: [
      { kind: "stage", glyph: "▬", label: "Sân khấu", hint: "Không bao giờ thành vé" },
      { kind: "aisle", glyph: "║", label: "Lối đi", hint: "Khoảng trống giữa các khu" },
      { kind: "door", glyph: "⌸", label: "Cửa", hint: "Cửa vào khu vực" },
      { kind: "bar", glyph: "▤", label: "Quầy", hint: "Quầy bar hoặc quầy phục vụ" },
      { kind: "text", glyph: "T", label: "Ghi chú", hint: "Chữ tự do trên sơ đồ" },
    ],
  },
  {
    // The facility markers. They were reachable from the old element palette and must stay reachable,
    // or retiring that palette would quietly remove seven kinds the database still supports.
    title: "Tiện ích",
    items: [
      { kind: "exit", glyph: "EX", label: "Thoát hiểm", hint: "Lối thoát hiểm" },
      { kind: "restroom", glyph: "WC", label: "Vệ sinh", hint: "Nhà vệ sinh" },
      { kind: "food_drink", glyph: "F&B", label: "Ăn uống", hint: "Đồ ăn và nước uống" },
      { kind: "smoking", glyph: "HT", label: "Hút thuốc", hint: "Khu vực hút thuốc" },
      { kind: "first_aid", glyph: "SC", label: "Sơ cứu", hint: "Điểm sơ cứu" },
      { kind: "lift_stairs", glyph: "TH", label: "Thang", hint: "Thang máy hoặc cầu thang" },
      { kind: "wheelchair", glyph: "XL", label: "Xe lăn", hint: "Lối dành cho xe lăn" },
    ],
  },
];

/** The named shapes, in the order they read as a family: boxes, then curves, then corners. */
const SHAPES: { geometry: Exclude<BlockGeometry, "free">; glyph: string; label: string }[] = [
  { geometry: "rect", glyph: "▭", label: "Chữ nhật" },
  { geometry: "square", glyph: "◻", label: "Vuông" },
  { geometry: "circle", glyph: "◯", label: "Tròn" },
  { geometry: "oval", glyph: "⬭", label: "Bầu dục" },
  { geometry: "triangle", glyph: "△", label: "Tam giác" },
  { geometry: "hexagon", glyph: "⬡", label: "Lục giác" },
];

/** Distinguishable at a glance on the dark canvas, and far enough apart to name zones by colour. */
const COLORS = ["#D93025", "#F7A97C", "#BFC0F2", "#FBD0DC", "#4C9A6B", "#8A0C24"] as const;

const item =
  "flex items-center gap-2 border-2 border-beige-kem/40 px-2 py-1.5 text-left text-xs text-beige-kem/80 transition hover:border-beige-kem hover:text-beige-kem disabled:opacity-40";

export default function BlockPalette({
  onAdd,
  onDraw,
  drawing,
  color,
  onColor,
  colorTarget,
  disabled,
  remaining,
  sections,
  categories,
  pinned,
  resolved,
  onPin,
}: {
  onAdd: (kind: BlockKind, geometry?: Exclude<BlockGeometry, "free">) => void;
  /** Enter or leave free-hand drawing, where the organizer places the outline point by point. */
  onDraw: () => void;
  drawing: boolean;
  /** The swatch to show as active: the selection's colour, else the one the next block will take. */
  color: string | null;
  onColor: (color: string | null) => void;
  /** How many selected blocks a colour would apply to — 0 means the swatches set a default instead. */
  colorTarget: number;
  disabled: boolean;
  /** Seats left before the layout ceiling, so the limit is visible before it bites. */
  remaining: number;
  /** The sections and classes a block can be put in — or not, which is the point of the `null` option. */
  sections: { id: number; name: string }[];
  categories: { id: number; name: string }[];
  /** What the organizer has PINNED. `undefined` means they have not said, and the block follows the
   *  selection as it always has. */
  pinned: BlockTarget;
  /** What that currently resolves to, so "Tự động" can say where it would actually put the block. */
  resolved: { sectionId: number | null; categoryId: number | null };
  onPin: (patch: Partial<BlockTarget>) => void;
}) {
  const nameOf = (pool: { id: number; name: string }[], id: number | null, none: string) =>
    pool.find((x) => x.id === id)?.name ?? none;

  /** `undefined` -> "auto", `null` -> "none", an id -> its digits. Three states, three values. */
  const valueOf = (v: number | null | undefined) => (v === undefined ? "auto" : v === null ? "none" : String(v));
  const parse = (v: string) => (v === "auto" ? undefined : v === "none" ? null : Number(v));

  return (
    <div className="border-2 border-beige-kem bg-surface-2 p-4">
      <div className="flex items-baseline justify-between gap-2">
        <h3 className="font-mono text-xs font-bold uppercase tracking-widest text-beige-kem/70">
          Thêm vào sơ đồ
        </h3>
        <span className="font-mono text-[10px] text-beige-kem/45">còn {remaining} ghế</span>
      </div>
      <p className="mt-1 text-[11px] leading-4 text-beige-kem/50">
        Khối mới được đặt ở giữa khung nhìn — kéo để dời, rồi sửa bố cục ở bảng thuộc tính.
      </p>

      {/* Where the next block lands. A CONTROL rather than a readout: a block does not have to belong
          to a section — the schema has allowed a section-less seat since 0024 and publish reports it —
          but with this resolved automatically there was no way to ask for one. */}
      <div className="mt-2 grid gap-1 border border-beige-kem/30 p-2">
        <label className="grid gap-0.5 font-mono text-[10px] text-beige-kem/60">
          Khối mới vào khu
          <select
            value={valueOf(pinned.sectionId)}
            onChange={(e) => onPin({ sectionId: parse(e.target.value) })}
            disabled={disabled}
            className="border border-beige-kem/40 bg-surface-2 px-1.5 py-1 text-[11px] text-beige-kem disabled:opacity-40"
          >
            <option value="auto">Tự động ({nameOf(sections, resolved.sectionId, "không thuộc khu nào")})</option>
            <option value="none">Không thuộc khu nào</option>
            {sections.map((x) => (
              <option key={x.id} value={x.id}>
                {x.name}
              </option>
            ))}
          </select>
        </label>
        <label className="grid gap-0.5 font-mono text-[10px] text-beige-kem/60">
          Hạng ghế
          <select
            value={valueOf(pinned.categoryId)}
            onChange={(e) => onPin({ categoryId: parse(e.target.value) })}
            disabled={disabled}
            className="border border-beige-kem/40 bg-surface-2 px-1.5 py-1 text-[11px] text-beige-kem disabled:opacity-40"
          >
            <option value="auto">Tự động ({nameOf(categories, resolved.categoryId, "chưa xếp hạng")})</option>
            <option value="none">Chưa xếp hạng ghế</option>
            {categories.map((x) => (
              <option key={x.id} value={x.id}>
                {x.name}
              </option>
            ))}
          </select>
        </label>
        {(pinned.sectionId === null || pinned.categoryId === null) && (
          <p className="text-[10px] leading-4 text-beige-kem/50">
            Ghế chưa có khu vực hoặc hạng ghế vẫn lưu được, nhưng phải xếp xong mới xuất bản được.
          </p>
        )}
      </div>

      {GROUPS.map((group) => (
        <div key={group.title} className="mt-3">
          <p className="font-mono text-[10px] uppercase tracking-wider text-beige-kem/45">
            {group.title}
          </p>
          <div className="mt-1 grid grid-cols-2 gap-1">
            {group.items.map((it) => (
              <button
                key={it.kind}
                disabled={disabled}
                title={`${it.hint} — bấm để thêm vào giữa khung nhìn, hoặc kéo thả vào đúng chỗ`}
                draggable={!disabled}
                onDragStart={(e) => {
                  e.dataTransfer.setData(BLOCK_DRAG_TYPE, formatBlockDrag(it.kind));
                  e.dataTransfer.effectAllowed = "copy";
                }}
                onClick={() => onAdd(it.kind)}
                className={item}
              >
                <span aria-hidden="true" className="text-base leading-none">
                  {it.glyph}
                </span>
                <span className="min-w-0 truncate">{it.label}</span>
              </button>
            ))}
          </div>
        </div>
      ))}

      {/* ---- Shapes ---------------------------------------------------------------------------- */}
      <div className="mt-3">
        <p className="font-mono text-[10px] uppercase tracking-wider text-beige-kem/45">Hình khối</p>
        <div className="mt-1 grid grid-cols-3 gap-1">
          {SHAPES.map((s) => (
            <button
              key={s.geometry}
              disabled={disabled}
              title={`${s.label} — bấm để thêm, hoặc kéo thả vào đúng chỗ. Kéo từng điểm trên sơ đồ để sửa lại.`}
              draggable={!disabled}
              onDragStart={(e) => {
                e.dataTransfer.setData(BLOCK_DRAG_TYPE, formatBlockDrag("shape", s.geometry));
                e.dataTransfer.effectAllowed = "copy";
              }}
              onClick={() => onAdd("shape", s.geometry)}
              className="flex flex-col items-center gap-0.5 border-2 border-beige-kem/40 px-1 py-1.5 text-[10px] text-beige-kem/80 transition hover:border-beige-kem hover:text-beige-kem disabled:opacity-40"
            >
              <span aria-hidden="true" className="text-base leading-none">
                {s.glyph}
              </span>
              <span className="min-w-0 truncate">{s.label}</span>
            </button>
          ))}
        </div>
        <button
          disabled={disabled}
          onClick={onDraw}
          aria-pressed={drawing}
          title="Đặt từng điểm trên sơ đồ, bấm lại điểm đầu để khép hình"
          className={`mt-1 w-full ${item} ${drawing ? "border-burgundy bg-burgundy/20 text-beige-kem" : ""}`}
        >
          <span className="min-w-0 truncate">{drawing ? "Đang vẽ — Esc để dừng" : "Vẽ tự do"}</span>
        </button>
      </div>

      {/* ---- Colour ---------------------------------------------------------------------------- */}
      <div className="mt-3">
        <p className="font-mono text-[10px] uppercase tracking-wider text-beige-kem/45">
          {/* Named for what the click will actually do, so a swatch never silently paints the wrong
              thing: with a selection it repaints it, without one it sets what the next block takes. */}
          {colorTarget > 0 ? `Màu · ${colorTarget} khối đang chọn` : "Màu cho khối mới"}
        </p>
        <div className="mt-1 flex flex-wrap gap-1">
          {COLORS.map((c) => (
            <button
              key={c}
              disabled={disabled}
              aria-label={`Màu ${c}`}
              aria-pressed={(color ?? "").toLowerCase() === c.toLowerCase()}
              onClick={() => onColor(c)}
              style={{ backgroundColor: c }}
              className={`h-7 w-7 border-2 transition disabled:opacity-40 ${ (color ?? "").toLowerCase() === c.toLowerCase()
                  ? "border-beige-kem"
                  : "border-transparent hover:border-beige-kem/50"
              }`}
            />
          ))}
          <button
            disabled={disabled}
            onClick={() => onColor(null)}
            aria-pressed={!color}
            title="Dùng màu mặc định của giao diện"
            className={`h-7 border-2 px-2 font-mono text-[10px] transition disabled:opacity-40 ${ color ? "border-transparent text-beige-kem/50" : "border-beige-kem text-beige-kem"
            }`}
          >
            Mặc định
          </button>
        </div>
        <p className="mt-1 text-[10px] leading-4 text-beige-kem/45">
          Màu áp cho sân khấu, hình khối, khu đứng và tiện ích. Ghế lấy màu theo hạng ghế.
        </p>
      </div>
    </div>
  );
}
