/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type { BlockKind } from "@/shared/catalog/seatmap-document";

/**
 * What the organizer can add to a chart.
 *
 * One list rather than the three palettes it replaces (`ElementPalette`, `TablePalette` and the
 * drawing-tool rail): a stage, a block of seats and a GA zone are all just blocks, and splitting them
 * across panels meant the organizer had to know which kind of thing they wanted before they could find
 * where to add it.
 *
 * Tables are absent on purpose. Their seats are generated by the server so they sit outside the table's
 * edge, so they keep their own endpoint and their own palette; putting them here would imply they work
 * like the rest, and then a re-count would behave differently from every other block.
 */

const GROUPS: { title: string; items: { kind: BlockKind; glyph: string; label: string; hint: string }[] }[] = [
  {
    title: "Ghế",
    items: [
      { kind: "seating-block", glyph: "▦", label: "Khối ghế", hint: "Nhiều hàng × nhiều ghế, sửa lại được sau" },
      { kind: "single-row", glyph: "▭", label: "Một hàng", hint: "Một hàng ghế thẳng" },
      { kind: "curved-row", glyph: "◠", label: "Hàng cong", hint: "Các hàng uốn theo bán kính và góc cung" },
      { kind: "individual-seat", glyph: "•", label: "Ghế lẻ", hint: "Một ghế đơn, đặt ở đâu cũng được" },
    ],
  },
  {
    title: "Khu đứng",
    items: [{ kind: "ga-zone", glyph: "▩", label: "Khu đứng", hint: "Bán theo sức chứa, không theo từng ghế" }],
  },
  {
    title: "Trang trí",
    items: [
      { kind: "stage", glyph: "▬", label: "Sân khấu", hint: "Không bao giờ thành vé" },
      { kind: "aisle", glyph: "║", label: "Lối đi", hint: "Khoảng trống giữa các khu" },
      { kind: "door", glyph: "⌸", label: "Cửa", hint: "Cửa vào khu vực" },
      { kind: "bar", glyph: "▤", label: "Quầy", hint: "Quầy bar hoặc quầy phục vụ" },
      { kind: "text", glyph: "T", label: "Ghi chú", hint: "Chữ tự do trên sơ đồ" },
      { kind: "shape", glyph: "⬡", label: "Hình khối", hint: "Đường bao hoặc vách ngăn" },
    ],
  },
  {
    // The facility markers. They were reachable from the old element palette and must stay reachable,
    // or retiring that palette would quietly remove seven kinds the database still supports.
    title: "Tiện ích",
    items: [
      { kind: "exit", glyph: "⇥", label: "Thoát hiểm", hint: "Lối thoát hiểm" },
      { kind: "restroom", glyph: "⛨", label: "Vệ sinh", hint: "Nhà vệ sinh" },
      { kind: "food_drink", glyph: "☕", label: "Ăn uống", hint: "Đồ ăn và nước uống" },
      { kind: "smoking", glyph: "◍", label: "Hút thuốc", hint: "Khu vực hút thuốc" },
      { kind: "first_aid", glyph: "✚", label: "Sơ cứu", hint: "Điểm sơ cứu" },
      { kind: "lift_stairs", glyph: "⇕", label: "Thang", hint: "Thang máy hoặc cầu thang" },
      { kind: "wheelchair", glyph: "♿", label: "Xe lăn", hint: "Lối dành cho xe lăn" },
    ],
  },
];

export default function BlockPalette({
  onAdd,
  disabled,
  remaining,
}: {
  onAdd: (kind: BlockKind) => void;
  disabled: boolean;
  /** Seats left before the layout ceiling, so the limit is visible before it bites. */
  remaining: number;
}) {
  return (
    <div className="rounded-2xl border-2 border-beige-kem bg-surface-2 p-4">
      <div className="flex items-baseline justify-between gap-2">
        <h3 className="font-mono text-xs font-bold uppercase tracking-widest text-beige-kem/70">
          Thêm vào sơ đồ
        </h3>
        <span className="font-mono text-[10px] text-beige-kem/45">còn {remaining} ghế</span>
      </div>
      <p className="mt-1 text-[11px] leading-4 text-beige-kem/50">
        Khối mới được đặt ở giữa khung nhìn — kéo để dời, rồi sửa bố cục ở bảng thuộc tính.
      </p>

      {GROUPS.map((group) => (
        <div key={group.title} className="mt-3">
          <p className="font-mono text-[10px] uppercase tracking-wider text-beige-kem/45">
            {group.title}
          </p>
          <div className="mt-1 grid grid-cols-2 gap-1">
            {group.items.map((item) => (
              <button
                key={item.kind}
                disabled={disabled}
                title={item.hint}
                onClick={() => onAdd(item.kind)}
                className="flex items-center gap-2 rounded-lg border-2 border-beige-kem/40 px-2 py-1.5 text-left text-xs text-beige-kem/80 transition hover:border-beige-kem hover:text-beige-kem disabled:opacity-40"
              >
                <span aria-hidden="true" className="text-base leading-none">
                  {item.glyph}
                </span>
                <span className="min-w-0 truncate">{item.label}</span>
              </button>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
